# Generated by Django 3.1.3 on 2020-12-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('is_busy', models.BooleanField(default=False)),
                ('way', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('addres', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('stock_balance', models.ImageField(default=0, upload_to='')),
            ],
        ),
    ]
