# Generated by Django 3.1.3 on 2020-12-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_balance',
            field=models.IntegerField(default=0),
        ),
    ]
