# Generated by Django 3.1.3 on 2020-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201225_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='products',
            field=models.CharField(default='', max_length=200),
        ),
    ]
