# Generated by Django 3.1.3 on 2020-12-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delivery_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='courier',
            field=models.CharField(default='', max_length=200),
        ),
    ]
